version: "2"
linters:
  default: none
  enable:
    - err113
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gosec
    - nakedret
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
  disable:
    - noinlineerr
  settings:
    gocyclo:
      min-complexity: 15
    varnamelen:
      ignore-decls:
        - fd uintptr
    wrapcheck:
      ignore-package-globs:
        - github.com/kzemek/go-mmproxy/*
