version: "2"
linters:
  default: none
  enable:
    - err113
    - errcheck
    - errname
    - errorlint
    - gochecknoglobals
    - gochecknoinits
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
  disable:
    - noinlineerr
  settings:
    wrapcheck:
      ignore-package-globs:
        - github.com/kzemek/go-mmproxy/*
    varnamelen:
      ignore-decls:
        - fd uintptr
